language: python
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6

install:
 - pip install -U pip
 - pip install -U black flake8
 - pip install -U -r requirements.txt
 - wget https://raw.githubusercontent.com/hugovk/flickr-tools/master/flickr_utils.py

script:
 # Unit tests
 - python test_onthisday.py

 # Static analysis
 - rm flickr_utils.py
 - flake8 --statistics --count
 - black --check --diff .
